apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-benchmarker
  labels:
    app: rabbit-test-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-test-tool
  template:
    metadata:
      labels:
        app: rabbit-test-tool
    spec:
      containers:
      - name: rabbit-test-tool
        image: pivotalrabbitmq/rabbittesttool:latest
        env:
          - name: RMQ_USER
            valueFrom:
              secretKeyRef:
                name: benchmark-default-user
                key: name
          - name: RMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: benchmark-default-user
                key: password
          - name: INFLUX_USER
            valueFrom:
              secretKeyRef:
                name: influx-user
                key: name
          - name: INFLUX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influx-user
                key: password
        volumeMounts:
        - name: topology-file
          mountPath: /etc/config/topology.json
          subPath: topology.json
          readOnly: true
        - name: policy-file
          mountPath: /etc/config/policy.json
          subPath: policy.json
          readOnly: true
        - name: config-file
          mountPath: /etc/config/config.json
          subPath: config.json
          readOnly: true
        command: ["java"]
        args:
        - "-jar rabbittesttool-1.1-SNAPSHOT-jar-with-dependencies.jar"
        - "--broker-hosts $BENCHMARK_SERVICE_HOST"
        - "--broker-user $RMQ_USER"
        - "--broker-password $RMQ_PASSWORD"
        - "--metrics-influx-user $INFLUX_USER"
        - "--metrics-influx-password $INFLUX_PASSWORD"
        - "--topology /etc/config/topology.json"
        - "--policies /etc/config/policy.json"
        - "--config-file /etc/config/config.json"
    volumes:
    - name: topology-file
      configMap:
        name: topology-config
    - name: policy-file
      configMap:
        name: policy-config
    - name: config-file
        configMap:
          name: test-config
