#@ load("@ytt:data", "data")
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: topology-config
data:
  topology.json: #@ data.read("topology.json")
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: policy-config
data:
  policy.json: #@ data.read("policy.json")
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: benchmark-config
data:
  config.json: #@ data.read("config.json")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rabbit-benchmarker
spec:
  completions: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: rabbit-test-tool
        image: pivotalrabbitmq/rabbittesttool:latest
        env:
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: benchmark-default-user
              key: username
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: benchmark-default-user
              key: password
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: benchmark-data-influxdb-auth
              key: influxdb-user
        - name: INFLUX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: benchmark-data-influxdb-auth
              key: influxdb-password
        volumeMounts:
        - name: topology-file
          mountPath: /etc/config/topology.json
          subPath: topology.json
          readOnly: true
        - name: policy-file
          mountPath: /etc/config/policy.json
          subPath: policy.json
          readOnly: true
        - name: config-file
          mountPath: /etc/config/config.json
          subPath: config.json
          readOnly: true
        args:
        - "--broker-user $(RMQ_USER)"
        - "--broker-password $(RMQ_PASSWORD)"
        - "--metrics-influx-user $(INFLUX_USER)"
        - "--metrics-influx-password $(INFLUX_PASSWORD)"
        - "--topology /etc/config/topology.json"
        - "--policies /etc/config/policy.json"
        - "--config-file /etc/config/config.json"
      volumes:
      - name: topology-file
        configMap:
          name: topology-config
      - name: policy-file
        configMap:
          name: policy-config
      - name: config-file
        configMap:
          name: benchmark-config
