apiVersion: v1
kind: Secret
metadata:
  name: telegraf-operator-classes
  namespace: telegraf-operator
classes:
  default: "infra"
  data:
    infra: |+
      [[outputs.influxdb]]
        urls = ["http://benchmark-data-influxdb.default.svc.cluster.local:8086"]
      [[outputs.file]]
        files = ["stdout"]
      [global_tags]
        type = "infra"
        env = "benchmark"
        hostname = "$HOSTNAME"
        nodename = "$NODENAME"